name: dev-feisty
channels:
  - conda-forge
  - nodefaults
dependencies:
  - codecov
  - dask<=2025.9
  - dask-mpi
  - dask-jobqueue
  - jupyter
  - jupyter-book<2
  - jupyter_client==6.1.12
  - jupyterlab
  - matplotlib
  - mpich
  - mpi4py
  - myst-nb
  - nb_conda_kernels
  - nbformat
  - nbsphinx
  - nc-time-axis
  - netcdf4
  - numpydoc
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pyyaml
  - ruamel.yaml<=0.18.17
  - scipy
  - sphinx-click
  - sphinxcontrib-autoyaml==1.1.3
  - xarray<=2025.9
  - zarr
  - pip:
      - '--editable=..'
